/* eslint-disable max-lines*/
import { Theme } from '@app/components/selectors/theme-selector/themes';

export interface Word {
    en: string;
    fr: string;
    de: string;
    themes: Theme[];
}

export const words: Word[] = [
    {
        en: 'fast',
        fr: 'rapide',
        de: 'schnell',
        themes: [Theme.Adjectives],
    },
    {
        en: 'juice',
        fr: 'jus',
        de: 'saft',
        themes: [Theme.Food],
    },
    {
        en: 'blue',
        fr: 'bleu',
        de: 'blau',
        themes: [Theme.Colors],
    },
    {
        en: 'sweet',
        fr: 'sucré',
        de: 'süß',
        themes: [Theme.Adjectives, Theme.Food],
    },
    {
        en: 'Old',
        fr: 'Vieux',
        de: 'Alt',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Poor',
        fr: 'Pauvre',
        de: 'Arm',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Bitter',
        fr: 'Amer',
        de: 'Bitter',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Thick',
        fr: 'Épais',
        de: 'Dick',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Dirty',
        fr: 'Sale',
        de: 'Dreckig',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Tight',
        fr: 'Serré',
        de: 'Eng',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Wrong',
        fr: 'Faux',
        de: 'Falsch',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Lazy',
        fr: 'Paresseux',
        de: 'Faul',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Friendly',
        fr: 'Amical',
        de: 'Freundlich',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Early',
        fr: 'Tôt',
        de: 'Früh',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Fresh',
        fr: 'Frais',
        de: 'Frisch',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Happy',
        fr: 'Content',
        de: 'Fröhlich',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Dangerous',
        fr: 'Dangereux',
        de: 'Gefährlich',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Healthy',
        fr: 'Sain',
        de: 'Gesund',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Smooth',
        fr: 'Lisse',
        de: 'Glatt',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Big',
        fr: 'Grand',
        de: 'Groß',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Good',
        fr: 'Bon',
        de: 'Gut',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Hot',
        fr: 'Chaud',
        de: 'Heiß',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Bright',
        fr: 'Brillant',
        de: 'Hell',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Crooked',
        fr: 'Tordu',
        de: 'Krumm',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Long',
        fr: 'Long',
        de: 'Lang',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Slow',
        fr: 'Lent',
        de: 'Langsam',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Loud',
        fr: 'Fort',
        de: 'Laut',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Motivated',
        fr: 'Motivé',
        de: 'Motiviert',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Tired',
        fr: 'Fatigué',
        de: 'Müde',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Clean',
        fr: 'Propre',
        de: 'Sauber',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Smart',
        fr: 'Intelligent',
        de: 'Schlau',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Pretty',
        fr: 'Joli',
        de: 'Schön',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Weak',
        fr: 'Faible',
        de: 'Schwach',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Dry',
        fr: 'Sec',
        de: 'Trocken',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Soft',
        fr: 'Mou',
        de: 'Weich',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Young',
        fr: 'Jeune',
        de: 'Jung',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Rich',
        fr: 'Riche',
        de: 'Reich',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Expensive',
        fr: 'Cher',
        de: 'Teuer',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Sweet',
        fr: 'Sucré',
        de: 'Süß',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Thin',
        fr: 'Mince',
        de: 'Dünn',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Clean',
        fr: 'Propre',
        de: 'Sauber',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Broad',
        fr: 'Large',
        de: 'Breit',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Right',
        fr: 'Correct',
        de: 'Richtig',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Late',
        fr: 'Tard',
        de: 'Spät',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Old',
        fr: 'Vieux',
        de: 'Alt',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Sad',
        fr: 'Triste',
        de: 'Traurig',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Sick',
        fr: 'Malade',
        de: 'Krank',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Small',
        fr: 'Petit',
        de: 'Klein',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Bad',
        fr: 'Mauvais',
        de: 'Schlecht',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Cold',
        fr: 'Froid',
        de: 'Kalt',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Dark',
        fr: 'Sombre',
        de: 'Dunkel',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Straight',
        fr: 'Droit',
        de: 'Gerade',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Short',
        fr: 'Court',
        de: 'Kurz',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Fast',
        fr: 'Rapide',
        de: 'Schnell',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Quiet',
        fr: 'Tranquille',
        de: 'Leise',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Awake',
        fr: 'Éveillé',
        de: 'Wach',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Dirty',
        fr: 'Sale',
        de: 'Dreckig',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Ugly',
        fr: 'Laid',
        de: 'Hässlich',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Strong',
        fr: 'Fort',
        de: 'Stark',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Wet',
        fr: 'Mouillé',
        de: 'Nass',
        themes: [Theme.Adjectives],
    },
    {
        en: 'Hard',
        fr: 'Dur',
        de: 'Hart',
        themes: [Theme.Adjectives],
    },
];
