/* eslint-disable max-lines*/
import { Theme } from '@app/components/selectors/theme-selector/themes';

export interface Word {
    en: string;
    fr: string;
    de: string;
    sv: string;
    themes: Theme[];
}

export const words: Word[] = [  
    { en: 'White',          fr: 'Blanc',            de: 'Weiß',                 sv: 'Vit',              themes: [Theme.Colors] },
    { en: 'Yellow',         fr: 'Jaune',            de: 'Gelb',                 sv: 'Gul',              themes: [Theme.Colors] },
    { en: 'Blue',           fr: 'Bleu',             de: 'Blau',                 sv: 'Blå',              themes: [Theme.Colors] },
    { en: 'Red',            fr: 'Rouge',            de: 'Rot',                  sv: 'Röd',              themes: [Theme.Colors] },
    { en: 'Green',          fr: 'Vert',             de: 'Grün',                 sv: 'Grön',             themes: [Theme.Colors] },
    { en: 'Black',          fr: 'Noir',             de: 'Schwarz',              sv: 'Svart',            themes: [Theme.Colors] },
    { en: 'Brown',          fr: 'Marron',           de: 'Braun',                sv: 'Brun',             themes: [Theme.Colors] },
    { en: 'Silver',         fr: 'Argent',           de: 'Silber',               sv: 'Silver',           themes: [Theme.Colors] },
    { en: 'Purple',         fr: 'Mauve',            de: 'Lila',                 sv: 'Lila',             themes: [Theme.Colors] },
    { en: 'Gray',           fr: 'Gris',             de: 'Grau',                 sv: 'Grå',              themes: [Theme.Colors] },
    { en: 'Orange',         fr: 'Orange',           de: 'Orange',               sv: 'Orange',           themes: [Theme.Colors] },
    { en: 'Arm',            fr: 'Bras',             de: 'Arm',                  sv: 'Ärm',              themes: [Theme.Body] },
    { en: 'Hair',           fr: 'Cheveu',           de: 'Haar',                 sv: 'Hår',              themes: [Theme.Body] },
    { en: 'Eyelash',        fr: 'Cil',              de: 'Wimper',               sv: 'Ögonhår',          themes: [Theme.Body] },
    { en: 'Heart',          fr: 'Cœur',             de: 'Herz',                 sv: 'Hjärta',           themes: [Theme.Body] },
    { en: 'Finger',         fr: 'Doigt',            de: 'Finger',               sv: 'Finger',           themes: [Theme.Body] },
    { en: 'Back',           fr: 'Dos',              de: 'Zurück',               sv: 'Tillbaka',         themes: [Theme.Body] },
    { en: 'Forehead',       fr: 'Front',            de: 'Stirn',                sv: 'Panna',            themes: [Theme.Body] },
    { en: 'Knee',           fr: 'Genou',            de: 'Knie',                 sv: 'Knä',              themes: [Theme.Body] },
    { en: 'Nose',           fr: 'Nez',              de: 'Nase',                 sv: 'Näsa',             themes: [Theme.Body] },
    { en: 'Nail',           fr: 'Ongle',            de: 'Nagel',                sv: 'Nagel',            themes: [Theme.Body] },
    { en: 'Foot',           fr: 'Pied',             de: 'Fuß',                  sv: 'Fot',              themes: [Theme.Body] },
    { en: 'Wrist',          fr: 'Poignet',          de: 'Handgelenk',           sv: 'Handled',          themes: [Theme.Body] },
    { en: 'Blood',          fr: 'Sang',             de: 'Blut',                 sv: 'Blod',             themes: [Theme.Body] },
    { en: 'Eyebrow',        fr: 'Sourcil',          de: 'Augenbraue',           sv: 'Ögonbryn',         themes: [Theme.Body] },
    { en: 'Face',           fr: 'Visage',           de: 'Gesicht',              sv: 'Ansikte',          themes: [Theme.Body] },
    { en: 'Eye',            fr: 'Oeil',             de: 'Auge',                 sv: 'Öga',              themes: [Theme.Body] },
    { en: 'Beard',          fr: 'Barbe',            de: 'Bart',                 sv: 'Skägg',            themes: [Theme.Body] },
    { en: 'Mouth',          fr: 'Bouche',           de: 'Mund',                 sv: 'Mun',              themes: [Theme.Body] },
    { en: 'Ankle',          fr: 'Cheville',         de: 'Knöchel',              sv: 'Vrist',            themes: [Theme.Body] },
    { en: 'Tooth',          fr: 'Dent',             de: 'Zahn',                 sv: 'Tand',             themes: [Theme.Body] },
    { en: 'Shoulder',       fr: 'Épaule',           de: 'Schulter',             sv: 'Axel',             themes: [Theme.Body] },
    { en: 'Buttocks',       fr: 'Fesses',           de: 'Gesäß',                sv: 'Rumpa',            themes: [Theme.Body] },
    { en: 'Throat',         fr: 'Gorge',            de: 'Kehle',                sv: 'Hals',             themes: [Theme.Body] },
    { en: 'Leg',            fr: 'Jambe',            de: 'Bein',                 sv: 'Ben',              themes: [Theme.Body] },
    { en: 'Cheek',          fr: 'Joue',             de: 'Wange',                sv: 'Kind',             themes: [Theme.Body] },
    { en: 'Tongue',         fr: 'Langue',           de: 'Zunge',                sv: 'Tunga',            themes: [Theme.Body] },
    { en: 'Lip',            fr: 'Lèvre',            de: 'Lippe',                sv: 'Läpp',             themes: [Theme.Body] },
    { en: 'Hand',           fr: 'Main',             de: 'Hand',                 sv: 'Hand',             themes: [Theme.Body] },
    { en: 'Moustache',      fr: 'Moustache',        de: 'Schnurrbart',          sv: 'Mustasch',         themes: [Theme.Body] },
    { en: 'Ear',            fr: 'Oreille',          de: 'Ohr',                  sv: 'Öra',              themes: [Theme.Body] },
    { en: 'Skin',           fr: 'Peau',             de: 'Haut',                 sv: 'Hud',              themes: [Theme.Body] },
    { en: 'Chest',          fr: 'Poitrine',         de: 'Brust',                sv: 'Bröst',            themes: [Theme.Body] },
    { en: 'Head',           fr: 'Tête',             de: 'Kopf',                 sv: 'Huvud',            themes: [Theme.Body] },
    { en: 'Cousin',         fr: 'Cousin',           de: 'Vetter',               sv: 'Kusin',            themes: [Theme.Family] },
    { en: 'Son',            fr: 'Fils',             de: 'Sohn',                 sv: 'Son',              themes: [Theme.Family] },
    { en: 'Brother',        fr: 'Frère',            de: 'Bruder',               sv: 'bror',             themes: [Theme.Family] },
    { en: 'Son-In-Law',     fr: 'Gendre',           de: 'Schwiegersohn',        sv: 'Svärson',          themes: [Theme.Family] },
    { en: 'Grandfather',    fr: 'Grand-Père',       de: 'Großvater',            sv: 'Farfar',           themes: [Theme.Family] },
    { en: 'Nephew',         fr: 'Neveu',            de: 'Neffe',                sv: 'Brorson',          themes: [Theme.Family] },
    { en: 'Uncle',          fr: 'Oncle',            de: 'Onkel',                sv: 'Farbror',          themes: [Theme.Family] },
    { en: 'Dad',            fr: 'Père',             de: 'Vater',                sv: 'Pappa',            themes: [Theme.Family] },
    { en: 'Grandson',       fr: 'Petit-Fils',       de: 'Enkel',                sv: 'Barnbarn',         themes: [Theme.Family] },
    { en: 'Cousin',         fr: 'Cousine',          de: 'Vetter',               sv: 'Kusin',            themes: [Theme.Family] },
    { en: 'Spouse',         fr: 'Épouse',           de: 'Ehepartner',           sv: 'Make',             themes: [Theme.Family] },
    { en: 'Daughter',       fr: 'Fille',            de: 'Mädchen',              sv: 'Dotter',           themes: [Theme.Family] },
    { en: 'Sister',         fr: 'Soeur',            de: 'Schwester',            sv: 'Syster',           themes: [Theme.Family] },
    { en: 'Bru',            fr: 'Bru',              de: 'Bru',                  sv: 'Bru',              themes: [Theme.Family] },
    { en: 'Grandmother',    fr: 'Grand-Mère',       de: 'Großmutter',           sv: 'Mormor',           themes: [Theme.Family] },
    { en: 'Niece',          fr: 'Nièce',            de: 'Nichte',               sv: 'Niece',            themes: [Theme.Family] },
    { en: 'Aunt',           fr: 'Tante',            de: 'Tante',                sv: 'Moster',           themes: [Theme.Family] },
    { en: 'Mother',         fr: 'Mère',             de: 'Mutter',               sv: 'Mor',              themes: [Theme.Family] },
    { en: 'Granddaughter',  fr: 'Petite-Fille',     de: 'Enkelin',              sv: 'Barnbarn',         themes: [Theme.Family] },
    { en: 'Husband',        fr: 'Époux',            de: 'Ehemann',              sv: 'Make',             themes: [Theme.Family] },
    { en: 'Child',          fr: 'Enfant',           de: 'Kind',                 sv: 'Barn',             themes: [Theme.Family] },
    { en: 'Balcony',        fr: 'Balcon',           de: 'Balkon',               sv: 'Balkong',          themes: [Theme.House] },
    { en: 'Office',         fr: 'Bureau',           de: 'Sekretariat',          sv: 'Kontor',           themes: [Theme.House] },
    { en: 'Corridor',       fr: 'Couloir',          de: 'Gang',                 sv: 'Korridor',         themes: [Theme.House] },
    { en: 'Stairs',         fr: 'Escalier',         de: 'Treppe',               sv: 'Trappa',           themes: [Theme.House] },
    { en: 'Sink',           fr: 'Évier',            de: 'Waschbecken',          sv: 'Handfat',          themes: [Theme.House] },
    { en: 'Oven',           fr: 'Four',             de: 'Ofen',                 sv: 'Ugn',              themes: [Theme.House] },
    { en: 'Microwave',      fr: 'Micro-Ondes',      de: 'Mikrowelle',           sv: 'Mikrovågsugn',     themes: [Theme.House] },
    { en: 'Garden',         fr: 'Jardin',           de: 'Garten',               sv: 'Trädgård',         themes: [Theme.House] },
    { en: 'Dishwasher',     fr: 'Lave-Vaisselle',   de: 'Geschirrspüler',       sv: 'Diskmaskin',       themes: [Theme.House] },
    { en: 'Bed',            fr: 'Lit',              de: 'Bett',                 sv: 'Säng',             themes: [Theme.House] },
    { en: 'Mirror',         fr: 'Miroir',           de: 'Spiegel',              sv: 'Spegel',           themes: [Theme.House] },
    { en: 'Ceiling',        fr: 'Plafond',          de: 'Decke',                sv: 'Tak',              themes: [Theme.House] },
    { en: 'Fridge',         fr: 'Réfrigérateur',    de: 'Kühlschrank',          sv: 'Kylskåp',          themes: [Theme.House] },
    { en: 'Basement',       fr: 'Sous-Sol',         de: 'Untergeschoss',        sv: 'Källare',          themes: [Theme.House] },
    { en: 'Cabinet',        fr: 'Armoire',          de: 'Kabinett',             sv: 'Skåp',             themes: [Theme.House] },
    { en: 'Bathtub',        fr: 'Baignoire',        de: 'Badewanne',            sv: 'Badkar',           themes: [Theme.House] },
    { en: 'Chair',          fr: 'Chaise',           de: 'Sessel',               sv: 'Stol',             themes: [Theme.House] },
    { en: 'Bedroom',        fr: 'Chambre',          de: 'Schlafzimmer',         sv: 'Sovrum',           themes: [Theme.House] },
    { en: 'Court',          fr: 'Cour',             de: 'Gericht',              sv: 'Domstol',          themes: [Theme.House] },
    { en: 'Food',           fr: 'Cuisine',          de: 'Lebensmittel',         sv: 'Mat',              themes: [Theme.House] },
    { en: 'Window',         fr: 'Fenêtre',          de: 'Fenster',              sv: 'Fönster',          themes: [Theme.House] },
    { en: 'Washer',         fr: 'Laveuse',          de: 'Unterlegscheibe',      sv: 'Bricka',           themes: [Theme.House] },
    { en: 'Gate',           fr: 'Porte',            de: 'Tor',                  sv: 'Port',             themes: [Theme.House] },
    { en: 'Bathroom',       fr: 'Salle De Bain',    de: 'Bad',                  sv: 'Badrum',           themes: [Theme.House] },
    { en: 'Table',          fr: 'Table',            de: 'Tabelle',              sv: 'Tabell',           themes: [Theme.House] },
    { en: 'Terrace',        fr: 'Terrasse',         de: 'Terrasse',             sv: 'Terrass',          themes: [Theme.House] },
    { en: 'Be',             fr: 'Être',             de: 'Sein',                 sv: 'Vara',             themes: [Theme.Verbs] },
    { en: 'Have',           fr: 'Avoir',            de: 'Haben',                sv: 'Ha',               themes: [Theme.Verbs] },
    { en: 'Do',             fr: 'Faire',            de: 'Machen',               sv: 'Do',               themes: [Theme.Verbs] },
    { en: 'Say',            fr: 'Dire',             de: 'Sagen',                sv: 'Säga',             themes: [Theme.Verbs] },
    { en: 'See',            fr: 'Voir',             de: 'Sehen',                sv: 'Ser',              themes: [Theme.Verbs] },
    { en: 'Take',           fr: 'Prendre',          de: 'Nehmen',               sv: 'Ta',               themes: [Theme.Verbs] },
    { en: 'Can',            fr: 'Pouvoir',          de: 'Kann',                 sv: 'Burk',             themes: [Theme.Verbs] },
    { en: 'Speak',          fr: 'Parler',           de: 'Sprechen',             sv: 'Tala',             themes: [Theme.Verbs] },
    { en: 'Know',           fr: 'Savoir',           de: 'Wissen',               sv: 'Känna till',       themes: [Theme.Verbs] },
    { en: 'Give',           fr: 'Donner',           de: 'Geben',                sv: 'Ge',               themes: [Theme.Verbs] },
    { en: 'Pass',           fr: 'Passer',           de: 'Bestehen',             sv: 'Passera',          themes: [Theme.Verbs] },
    { en: 'Put',            fr: 'Mettre',           de: 'Stellen',              sv: 'Sätta',            themes: [Theme.Verbs] },
    { en: 'Leave',          fr: 'Partir',           de: 'Verlassen',            sv: 'Lämna',            themes: [Theme.Verbs] },
    { en: 'Find',           fr: 'Trouver',          de: 'Finden',               sv: 'Hitta',            themes: [Theme.Verbs] },
    { en: 'Laugh',          fr: 'Rire',             de: 'Lachen',               sv: 'Skratt',           themes: [Theme.Verbs] },
    { en: 'Live',           fr: 'Vivre',            de: 'Leben',                sv: 'leva',             themes: [Theme.Verbs] },
    { en: 'Let',            fr: 'Laisser',          de: 'Lassen',               sv: 'Låta',             themes: [Theme.Verbs] },
    { en: 'Return',         fr: 'Retourner',        de: 'Rückkehr',             sv: 'Lämna tillbaka',   themes: [Theme.Verbs] },
    { en: 'Smile',          fr: 'Sourire',          de: 'Lächeln',              sv: 'Leende',           themes: [Theme.Verbs] },
    { en: 'Come',           fr: 'Venir',            de: 'Kommen',               sv: 'Komma',            themes: [Theme.Verbs] },
    { en: 'Understand',     fr: 'Comprendre',       de: 'Verstehen',            sv: 'Förstå',           themes: [Theme.Verbs] },
    { en: 'Think',          fr: 'Penser',           de: 'Überlegen',            sv: 'Tror',             themes: [Theme.Verbs] },
    { en: 'Believe',        fr: 'Croire',           de: 'Glauben',              sv: 'Tro',              themes: [Theme.Verbs] },
    { en: 'Hear',           fr: 'Entendre',         de: 'Hören',                sv: 'Höra',             themes: [Theme.Verbs] },
    { en: 'Hold',           fr: 'Tenir',            de: 'Halt',                 sv: 'Håll',             themes: [Theme.Verbs] },
    { en: 'Ask',            fr: 'Demander',         de: 'Fragen',               sv: 'Fråga',            themes: [Theme.Verbs] },
    { en: 'Remember',       fr: 'Souvenir',         de: 'Erinnerung',           sv: 'Kom ihåg',         themes: [Theme.Verbs] },
    { en: 'Go',             fr: 'Aller',            de: 'Gehen',                sv: 'Gå',               themes: [Theme.Verbs] },
    { en: 'Play',           fr: 'Jouer',            de: 'Spielen',              sv: 'Spela',            themes: [Theme.Verbs] },
    { en: 'Write',          fr: 'Écrire',           de: 'Schreiben',            sv: 'Skriva',           themes: [Theme.Verbs] },
    { en: 'Know',           fr: 'Connaître',        de: 'Wissen',               sv: 'Känna till',       themes: [Theme.Verbs] },
    { en: 'Become',         fr: 'Devenir',          de: 'Werden',               sv: 'Bli',              themes: [Theme.Verbs] },
    { en: 'Die',            fr: 'Mourir',           de: 'Versterben',           sv: 'Dö',               themes: [Theme.Verbs] },
    { en: 'Stay',           fr: 'Rester',           de: 'Bleiben',              sv: 'Stanna kvar',      themes: [Theme.Verbs] },
    { en: 'Enter',          fr: 'Entrer',           de: 'Eintreten',            sv: 'Stiga på',         themes: [Theme.Verbs] },
    { en: 'Eat',            fr: 'Manger',           de: 'Essen',                sv: 'Äta',              themes: [Theme.Verbs] },
    { en: 'Fall',           fr: 'Tomber',           de: 'Fallen',               sv: 'Falla',            themes: [Theme.Verbs] },
    { en: 'Shoot',          fr: 'Tirer',            de: 'Schießen',             sv: 'Skjuta',           themes: [Theme.Verbs] },
    { en: 'Read',           fr: 'Lire',             de: 'Lesen',                sv: 'Läsa',             themes: [Theme.Verbs] },
    { en: 'Follow',         fr: 'Suivre',           de: 'Folgen',               sv: 'Följ',             themes: [Theme.Verbs] },
    { en: 'Get',            fr: 'Obtenir',          de: 'Werden',               sv: 'Skaffa sig',       themes: [Theme.Verbs] },
    { en: 'Lose',           fr: 'Perdre',           de: 'Verlieren',            sv: 'Förlora',          themes: [Theme.Verbs] },
    { en: 'Explain',        fr: 'Expliquer',        de: 'Erklären',             sv: 'Förklara',         themes: [Theme.Verbs] },
    { en: 'Assure',         fr: 'Assurer',          de: 'Versichern',           sv: 'Försäkra',         themes: [Theme.Verbs] },
    { en: 'Serve',          fr: 'Servir',           de: 'Dienen',               sv: 'Tjäna',            themes: [Theme.Verbs] },
    { en: 'Carry',          fr: 'Porter',           de: 'Tragen',               sv: 'Bära',             themes: [Theme.Verbs] },
    { en: 'Show',           fr: 'Montrer',          de: 'Zeigen',               sv: 'Visa',             themes: [Theme.Verbs] },
    { en: 'Avoid',          fr: 'Éviter',           de: 'Vermeiden',            sv: 'Undvika',          themes: [Theme.Verbs] },
    { en: 'Arrive',         fr: 'Arriver',          de: 'Ankommen',             sv: 'Anlända',          themes: [Theme.Verbs] },
    { en: 'Want',           fr: 'Vouloir',          de: 'Wollen',               sv: 'Vilja',            themes: [Theme.Verbs] },
    { en: 'Acknowledge',    fr: 'Reconnaître',      de: 'Anerkennen',           sv: 'Erkänna',          themes: [Theme.Verbs] },
    { en: 'Ascend',         fr: 'Monter',           de: 'Aufsteigen',           sv: 'Stiga',            themes: [Theme.Verbs] },
    { en: 'Drink',          fr: 'Boire',            de: 'Getränk',              sv: 'Dryck',            themes: [Theme.Verbs] },
    { en: 'Forget',         fr: 'Oublier',          de: 'Vergessen',            sv: 'Glömma',           themes: [Theme.Verbs] },
    { en: 'Pose',           fr: 'Poser',            de: 'Posieren',             sv: 'Utgör',            themes: [Theme.Verbs] },
    { en: 'Like',           fr: 'Aimer',            de: 'Mögen',                sv: 'Tycka om',         themes: [Theme.Verbs] },
    { en: 'Stop',           fr: 'Arrêter',          de: 'Halt',                 sv: 'Sluta',            themes: [Theme.Verbs] },
    { en: 'Feel',           fr: 'Sentir',           de: 'Fühlen',               sv: 'Känna',            themes: [Theme.Verbs] },
    { en: 'Reach',          fr: 'Atteindre',        de: 'Erreichen',            sv: 'Nå',               themes: [Theme.Verbs] },
    { en: 'Change',         fr: 'Changer',          de: 'Wechseln',             sv: 'Förändra',         themes: [Theme.Verbs] },
    { en: 'Sleep',          fr: 'Dormir',           de: 'Schlafen',             sv: 'Sova',             themes: [Theme.Verbs] },
];
